name: mobile_app
description: "Buy and Sell Market Place With Escrow"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  onboarding: ^4.0.2
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.0.13
  intl: ^0.19.0
  provider: ^6.0.4
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  pinput: ^4.0.0
  awesome_dialog: ^3.2.1
  webview_flutter: ^4.9.0
  flutter_rating_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
